# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk]
    runs-on: macos-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - run: ./gradlew check build publishToMavenLocal --stacktrace --parallel --warning-mode=fail
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Maven Local
          path: /root/.m2/repository